# Generated by Django 5.1.4 on 2025-01-29 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.SmallIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
