# Generated by Django 5.1.4 on 2025-01-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_adress_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='zip',
        ),
    ]
