# Generated by Django 5.1.4 on 2025-01-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_adress_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='zip',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
