# Generated by Django 5.1.4 on 2025-01-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_adress_zip'),
    ]

    operations = [
    ]
